#!/usr/bin/env bash

SOURCE_DIR="`pwd`"
BUILD_DIR="`pwd`/build/Release"

ncpus=1
case "`uname`" in
  Darwin* )
    ncpus=`sysctl -n hw.ncpu`
    ;;
  Linux*)
    ncpus=$(lscpu -p | egrep -v '^#' | wc -l)
    ;;
esac

echo "Will make with \"-j $ncpus\"."

if [ -d "$BUILD_DIR" ] ; then
    echo "Build directory ($BUILD_DIR) exists, removing."
    rm -rf $BUILD_DIR
fi

mkdir -p $BUILD_DIR

(cd $BUILD_DIR && cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$BUILD_DIR/reactivestreams $SOURCE_DIR && make clean && make -j "$ncpus" all && ctest -V -C Release && make install)
